[theme]

# Primary accent for interactive elements
primaryColor = 'rebeccapurple'

# Background color for the main content area
backgroundColor = 'white'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F8F8F8'

# Color used for almost all text
textColor = '#204B5E'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
